[webserver]
ec2-13-39-84-48.eu-west-3.compute.amazonaws.com ansible_ssh_user=jenkins
ansible_ssh_private_key_file=~/.ssh/id_rsa.pem 
ansible_user=jenkins 
ansible_ssh_extra_args=’-o StrictHostKeyChecking=no’