- hosts: webserver
  become: yes
  tasks:
    - name: verif presence apache
      package:
        name: apache2
        state: present
    - name: ajout page index.html
      template:
        dest: /var/www/html/index.html
        src: index.html
        owner: root
        group: root
        mode: 0644
    - name: démarrage apache
      service:
        name: "{{ webserver_package_name }}"
        state: started
        enabled: yes